"""empty message

Revision ID: 746afef364b6
Revises: 07e2a9646966
Create Date: 2022-07-04 22:25:03.638976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746afef364b6'
down_revision = '07e2a9646966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    # ### end Alembic commands ###
